### ISSUE TITLE
influxdb-relay doesn't build with Go versions older than 1.5

### ISSUE THREAD

**Issue by lqx302** [influxdata/influxdb-relay#8]
```
go install github.com/influxdata/influxdb-relay
warning: GOPATH set to GOROOT (/usr/lib/golang) has no effect
# github.com/influxdata/influxdb-relay/relay
/usr/lib/golang/src/github.com/influxdata/influxdb-relay/relay/udp.go:210: undefined: bytes.LastIndexByte
```

**Comment by jonseymour** [comment]
This issue is caused by attempting to compile influxdb-relay with an older version of go. You might try with go1.6

**Comment by lqx302** [comment]
Test ok,Thanks

**Comment by joelegasse** [comment]
`bytes.LastIndexByte` is a Go 1.5+ function, I'll add a note to the README
